
import type { WeddingHall, Booking } from './types';

export const MOCK_HALLS: WeddingHall[] = [
  {
    id: 1,
    name: 'The Royal Palace',
    address: '123 Main Gulberg Blvd, Gulberg III',
    area: 'Gulberg',
    city: 'Lahore',
    venueType: 'Palace',
    capacity: { min: 300, max: 1000 },
    pricePerEvent: 500000,
    rating: 4.8,
    reviews: [
      { author: 'Ahmed K.', rating: 5, comment: 'Absolutely stunning venue with impeccable service. Made our day truly special.' },
      { author: 'Fatima S.', rating: 4.5, comment: 'Beautiful decor and spacious. The catering was also excellent.' },
    ],
    images: ['https://picsum.photos/seed/hall1/1200/800', 'https://picsum.photos/seed/hall1-2/1200/800', 'https://picsum.photos/seed/hall1-3/1200/800'],
    facilities: ['Air Conditioning', 'Valet Parking', 'In-house Catering', 'Stage Decor', 'Bridal Room'],
    location: { lat: 31.5204, lng: 74.3587 },
  },
  {
    id: 2,
    name: 'Oceanview Banquet',
    address: 'D-8, Block 4, Clifton',
    area: 'Clifton',
    city: 'Karachi',
    venueType: 'Destination',
    capacity: { min: 200, max: 600 },
    pricePerEvent: 450000,
    rating: 4.6,
    reviews: [
      { author: 'Bilal M.', rating: 5, comment: 'The sea view is breathtaking. Highly recommended for a memorable event.' },
      { author: 'Aisha J.', rating: 4, comment: 'Good service, but the parking can be a bit challenging on weekends.' },
    ],
    images: ['https://picsum.photos/seed/hall2/1200/800', 'https://picsum.photos/seed/hall2-2/1200/800', 'https://picsum.photos/seed/hall2-3/1200/800'],
    facilities: ['Sea View', 'Air Conditioning', 'In-house Catering', 'Sound System'],
    location: { lat: 24.8258, lng: 67.0305 },
  },
  {
    id: 3,
    name: 'Margalla Greens',
    address: 'Street 5, Sector E-11/4',
    area: 'E-11',
    city: 'Islamabad',
    venueType: 'Outdoor',
    capacity: { min: 100, max: 400 },
    pricePerEvent: 350000,
    rating: 4.9,
    reviews: [
      { author: 'Saad A.', rating: 5, comment: 'Perfect for intimate gatherings. The lush green surroundings are beautiful.' },
      { author: 'Hira T.', rating: 5, comment: 'Exceptional service and management. They took care of everything.' },
    ],
    images: ['https://picsum.photos/seed/hall3/1200/800', 'https://picsum.photos/seed/hall3-2/1200/800', 'https://picsum.photos/seed/hall3-3/1200/800'],
    facilities: ['Outdoor Seating', 'Air Conditioning', 'Valet Parking', 'Decor Services'],
    location: { lat: 33.7029, lng: 72.9754 },
  },
  {
    id: 4,
    name: 'The Grand Ballroom',
    address: 'Sector Y, Phase 3, DHA',
    area: 'DHA',
    city: 'Lahore',
    venueType: 'Banquet',
    capacity: { min: 500, max: 1500 },
    pricePerEvent: 800000,
    rating: 4.7,
    reviews: [
      { author: 'Usman R.', rating: 5, comment: 'If you want a grand wedding, this is the place. Huge hall and amazing lighting.' },
      { author: 'Zainab Q.', rating: 4.5, comment: 'Very professional staff. The food was top-notch.' },
    ],
    images: ['https://picsum.photos/seed/hall4/1200/800', 'https://picsum.photos/seed/hall4-2/1200/800', 'https://picsum.photos/seed/hall4-3/1200/800'],
    facilities: ['Air Conditioning', 'Valet Parking', 'In-house Catering', 'Large Stage', 'LED Screens'],
    location: { lat: 31.4704, lng: 74.4111 },
  },
  {
    id: 5,
    name: 'Crystal Marquee',
    address: 'Plot 7, Street 1, F-10/3',
    area: 'F-10',
    city: 'Islamabad',
    venueType: 'Marquee',
    capacity: { min: 250, max: 700 },
    pricePerEvent: 400000,
    rating: 4.5,
    reviews: [
      { author: 'Ali H.', rating: 4, comment: 'The marquee setup is very elegant. Good for all weather conditions.' },
      { author: 'Sana B.', rating: 5, comment: 'Loved the transparent ceiling! It felt magical at night.' },
    ],
    images: ['https://picsum.photos/seed/hall5/1200/800', 'https://picsum.photos/seed/hall5-2/1200/800', 'https://picsum.photos/seed/hall5-3/1200/800'],
    facilities: ['Air Conditioning', 'Heating', 'In-house Catering', 'Decor Services', 'Parking'],
    location: { lat: 33.6938, lng: 73.0039 },
  },
   {
    id: 6,
    name: 'Shehnai Banquet Hall',
    address: 'Block L, North Nazimabad Town',
    area: 'North Nazimabad',
    city: 'Karachi',
    venueType: 'Banquet',
    capacity: { min: 400, max: 900 },
    pricePerEvent: 300000,
    rating: 4.3,
    reviews: [
      { author: 'Imran F.', rating: 4, comment: 'Very reasonable price for the size and services offered. Great value.' },
      { author: 'Nida W.', rating: 4.5, comment: 'The management was very cooperative. Food was decent.' },
    ],
    images: ['https://picsum.photos/seed/hall6/1200/800', 'https://picsum.photos/seed/hall6-2/1200/800', 'https://picsum.photos/seed/hall6-3/1200/800'],
    facilities: ['Air Conditioning', 'In-house Catering', 'Stage Decor', 'Parking Area'],
    location: { lat: 24.9271, lng: 67.0254 },
  },
  {
    id: 7,
    name: 'The Pearl Continental Marquee',
    address: 'Shahrah-e-Quaid-e-Azam, Mall Road',
    area: 'Mall Road',
    city: 'Lahore',
    venueType: 'Marquee',
    capacity: { min: 500, max: 2000 },
    pricePerEvent: 1200000,
    rating: 4.9,
    reviews: [
      { author: 'Danish L.', rating: 5, comment: 'The epitome of luxury. Flawless execution and service.' },
      { author: 'Sobia A.', rating: 5, comment: 'Absolutely breathtaking. Worth every penny for a grand event.' },
    ],
    images: ['https://picsum.photos/seed/hall7/1200/800', 'https://picsum.photos/seed/hall7-2/1200/800'],
    facilities: ['Central Air Conditioning', 'Valet Parking', '5-Star Catering', 'Bridal Suite', 'Backup Generator'],
    location: { lat: 31.5656, lng: 74.3292 },
  },
  {
    id: 8,
    name: 'Serena Hotel Gardens',
    address: 'Khayaban-e-Suhrwardy, G-5/1',
    area: 'Khayaban-e-Suhrwardy',
    city: 'Islamabad',
    venueType: 'Outdoor',
    capacity: { min: 300, max: 800 },
    pricePerEvent: 950000,
    rating: 4.8,
    reviews: [
      { author: 'Faisal K.', rating: 5, comment: 'A magical outdoor setting with the best service in the city.' },
    ],
    images: ['https://picsum.photos/seed/hall8/1200/800', 'https://picsum.photos/seed/hall8-2/1200/800'],
    facilities: ['Landscaped Gardens', 'Valet Parking', 'Gourmet Catering', 'Weather Proofing option'],
    location: { lat: 33.7182, lng: 73.0722 },
  },
  {
    id: 9,
    name: 'Movenpick Grand Ballroom',
    address: 'Club Rd, Civil Lines',
    area: 'Club Road',
    city: 'Karachi',
    venueType: 'Banquet',
    capacity: { min: 400, max: 1200 },
    pricePerEvent: 1100000,
    rating: 4.7,
    reviews: [
      { author: 'Adil S.', rating: 4.5, comment: 'Classy, elegant, and very spacious. The staff is highly professional.' },
    ],
    images: ['https://picsum.photos/seed/hall9/1200/800'],
    facilities: ['Pillar-less Hall', 'Valet Parking', 'International Cuisine', 'Advanced Sound System'],
    location: { lat: 24.8475, lng: 67.0289 },
  },
  {
    id: 10,
    name: 'Nishat Hotel Emporium',
    address: 'Abdul Haque Rd, Johar Town',
    area: 'Johar Town',
    city: 'Lahore',
    venueType: 'Palace',
    capacity: { min: 600, max: 1800 },
    pricePerEvent: 1500000,
    rating: 4.9,
    reviews: [
      { author: 'Maria B.', rating: 5, comment: 'Unmatched grandeur and luxury. It feels like a royal wedding.' },
    ],
    images: ['https://picsum.photos/seed/hall10/1200/800', 'https://picsum.photos/seed/hall10-2/1200/800'],
    facilities: ['Valet Parking', 'In-house Catering', 'Large Stage', 'Bridal Room', 'Attached Mall'],
    location: { lat: 31.4647, lng: 74.2676 },
  },
  {
    id: 11,
    name: 'Blue Lagoon Resort',
    address: 'Hawks Bay Rd, Mauripur',
    area: 'Hawksbay',
    city: 'Karachi',
    venueType: 'Destination',
    capacity: { min: 150, max: 500 },
    pricePerEvent: 600000,
    rating: 4.4,
    reviews: [
      { author: 'Kamran A.', rating: 4, comment: 'A unique beachside experience. Great for a destination wedding feel.' },
    ],
    images: ['https://picsum.photos/seed/hall11/1200/800'],
    facilities: ['Beach Access', 'Private Huts', 'Catering Services', 'Parking'],
    location: { lat: 24.862, lng: 66.8615 },
  },
  {
    id: 12,
    name: 'Avari Towers Poolside',
    address: '242-244 Fatima Jinnah Rd, Civil Lines',
    area: 'Fatima Jinnah Road',
    city: 'Karachi',
    venueType: 'Outdoor',
    capacity: { min: 200, max: 600 },
    pricePerEvent: 750000,
    rating: 4.6,
    reviews: [
      { author: 'Sanam C.', rating: 5, comment: 'Stunning ambiance by the pool at night. Highly recommended.' },
    ],
    images: ['https://picsum.photos/seed/hall12/1200/800', 'https://picsum.photos/seed/hall12-2/1200/800'],
    facilities: ['Poolside Area', 'Valet Parking', 'In-house Catering', 'Decor Services'],
    location: { lat: 24.8569, lng: 67.0311 },
  },
  {
    id: 13,
    name: 'The Tulip Venue',
    address: '12-Z, Commercial, Phase 5, DHA',
    area: 'DHA Phase 5',
    city: 'Lahore',
    venueType: 'Banquet',
    capacity: { min: 200, max: 500 },
    pricePerEvent: 450000,
    rating: 4.2,
    reviews: [
      { author: 'Junaid I.', rating: 4, comment: 'Good for smaller, intimate events. The decor they provided was beautiful.' },
    ],
    images: ['https://picsum.photos/seed/hall13/1200/800'],
    facilities: ['Air Conditioning', 'Parking', 'In-house Catering', 'Stage Decor'],
    location: { lat: 31.478, lng: 74.394 },
  },
  {
    id: 14,
    name: 'Saidpur Village Courtyard',
    address: 'Saidpur Village Rd, Saidpur',
    area: 'Saidpur Village',
    city: 'Islamabad',
    venueType: 'Outdoor',
    capacity: { min: 100, max: 300 },
    pricePerEvent: 400000,
    rating: 4.7,
    reviews: [
      { author: 'Hina R.', rating: 5, comment: 'A very rustic and traditional feel. Perfect for a Mehndi night.' },
    ],
    images: ['https://picsum.photos/seed/hall14/1200/800'],
    facilities: ['Outdoor Seating', 'Traditional Decor', 'Live Music arrangement'],
    location: { lat: 33.7431, lng: 73.0642 },
  },
  {
    id: 15,
    name: 'Royal Palm Golf & Country Club',
    address: '52 Canal Bank Rd, Mughalpura',
    area: 'Canal Bank Road',
    city: 'Lahore',
    venueType: 'Outdoor',
    capacity: { min: 500, max: 2500 },
    pricePerEvent: 1800000,
    rating: 4.9,
    reviews: [
      { author: 'Osman K.', rating: 5, comment: 'The most beautiful outdoor venue in Lahore. Sprawling lawns and impeccable service.' },
    ],
    images: ['https://picsum.photos/seed/hall15/1200/800', 'https://picsum.photos/seed/hall15-2/1200/800'],
    facilities: ['Vast Lawns', 'Valet Parking', 'Premium Catering', 'Golf Course View'],
    location: { lat: 31.5037, lng: 74.3216 },
  },
  {
    id: 16,
    name: 'Garrison Golf & Country Club',
    address: 'Tufail Road, Lahore Cantt',
    area: 'Cantt',
    city: 'Lahore',
    venueType: 'Marquee',
    capacity: { min: 400, max: 1200 },
    pricePerEvent: 700000,
    rating: 4.4,
    reviews: [
      { author: 'Majid Khan', rating: 4.5, comment: 'Spacious marquee with beautiful surroundings. Great value for money.' },
    ],
    images: ['https://picsum.photos/seed/hall16/1200/800'],
    facilities: ['Air Conditioning', 'Large Parking', 'Panel Catering', 'Decor Services'],
    location: { lat: 31.5103, lng: 74.3854 },
  },
  {
    id: 17,
    name: 'Ambassador Hotel',
    address: '74 Davis Rd, Basti Nau',
    area: 'Davis Road',
    city: 'Lahore',
    venueType: 'Banquet',
    capacity: { min: 150, max: 400 },
    pricePerEvent: 250000,
    rating: 4.0,
    reviews: [
      { author: 'Tariq J.', rating: 4, comment: 'An old classic. Good for budget-conscious events without compromising quality.' },
    ],
    images: ['https://picsum.photos/seed/hall17/1200/800'],
    facilities: ['Air Conditioning', 'In-house Catering', 'Parking'],
    location: { lat: 31.5583, lng: 74.3323 },
  },
  {
    id: 18,
    name: 'Dreamworld Resort',
    address: 'Adjacent Block R, Gulshan-e-Maymar',
    area: 'Super Highway',
    city: 'Karachi',
    venueType: 'Destination',
    capacity: { min: 300, max: 3000 },
    pricePerEvent: 1000000,
    rating: 4.5,
    reviews: [
      { author: 'Yasir N.', rating: 4.5, comment: 'So much to do for guests. More than just a wedding venue, it\'s an experience.' },
    ],
    images: ['https://picsum.photos/seed/hall18/1200/800', 'https://picsum.photos/seed/hall18-2/1200/800'],
    facilities: ['Water Park Access', 'Chalet Stay', 'Multiple Lawns', 'In-house Catering'],
    location: { lat: 25.0456, lng: 67.2285 },
  },
  {
    id: 19,
    name: 'PAF Museum Lawns',
    address: 'PAF Faisal Air Base, Shahrah-e-Faisal',
    area: 'Shahrah-e-Faisal',
    city: 'Karachi',
    venueType: 'Outdoor',
    capacity: { min: 500, max: 1500 },
    pricePerEvent: 650000,
    rating: 4.3,
    reviews: [
      { author: 'Asif Z.', rating: 4, comment: 'Unique setting surrounded by aircraft. Very spacious and well-maintained.' },
    ],
    images: ['https://picsum.photos/seed/hall19/1200/800'],
    facilities: ['Large Lawns', 'Ample Parking', 'Catering Allowed', 'Security'],
    location: { lat: 24.8732, lng: 67.0945 },
  },
  {
    id: 20,
    name: 'The Venue',
    address: 'College Rd, F-6 Markaz',
    area: 'F-6 Markaz',
    city: 'Islamabad',
    venueType: 'Banquet',
    capacity: { min: 100, max: 350 },
    pricePerEvent: 380000,
    rating: 4.1,
    reviews: [
      { author: 'Sadia P.', rating: 4, comment: 'Cozy and elegant. Perfect for small functions. The food was surprisingly good.' },
    ],
    images: ['https://picsum.photos/seed/hall20/1200/800'],
    facilities: ['Air Conditioning', 'In-house Catering', 'Sound System', 'Valet Parking'],
    location: { lat: 33.7291, lng: 73.0768 },
  },
  {
    id: 21,
    name: 'Monal Restaurant',
    address: 'Pir Sohawa Rd, Islamabad',
    area: 'Pir Sohawa',
    city: 'Islamabad',
    venueType: 'Destination',
    capacity: { min: 50, max: 200 },
    pricePerEvent: 550000,
    rating: 4.8,
    reviews: [
      { author: 'Wajahat A.', rating: 5, comment: 'The view of Islamabad is simply unbeatable. An unforgettable experience for our guests.' },
    ],
    images: ['https://picsum.photos/seed/hall21/1200/800', 'https://picsum.photos/seed/hall21-2/1200/800'],
    facilities: ['City View', 'Terrace Seating', 'Gourmet Food', 'Valet Parking'],
    location: { lat: 33.7441, lng: 73.082 },
  },
];


// Assuming a logged in user with ID 1
export const MOCK_BOOKINGS: Booking[] = [
    {
        id: 1,
        hallId: 4,
        userId: 1,
        eventDate: '2024-09-15',
        eventType: 'Walima',
        status: 'Confirmed'
    },
    {
        id: 2,
        hallId: 8,
        userId: 1,
        eventDate: '2024-12-22',
        eventType: 'Shaadi',
        status: 'Confirmed'
    },
    {
        id: 3,
        hallId: 2,
        userId: 1,
        eventDate: '2024-04-05',
        eventType: 'Mehndi',
        status: 'Completed'
    }
];